In [1]:
import matplotlib.pyplot as plt
from sklearn import datasets
import numpy as np

In [2]:
iris = datasets.load_iris()

In [4]:
y = iris['target']
Y = y[:100]
x = iris['data']
X = x[:,1]

In [5]:
X = np.array(X) #Data
Y = np.array(Y) #labels

In [6]:
count = [0,0]
for i in Y:
    if i == 0:
        count[0] = count[0]+1
    if i == 1:
        count[1] = count[1]+1

In [7]:
alpha = [] #no. of examples in a class/in the two classes chosen
for i in count:
    alpha.append(i * 1.0 / len(Y))
print 'count', count
print 'alpha:',alpha

count [50, 50]
alpha: [0.5, 0.5]


In [9]:
sum1 = [0,0] #Sum of I(y(i)=j)*X(i) {Helps determining mew}
for i in range(len(Y)):
    if Y[i] == 0:
        sum1[0] = sum1[0]+X[i]
    if Y[i] == 1:
        sum1[1] = sum1[1]+X[i]

mew = [] #mean of classes
for i in range(len(sum1)):
    mew.append(sum1[i]/count[i])
    
print 'mean of classes:', mew

mean of classes: [3.4180000000000006, 2.7700000000000005]


In [11]:
sum2 = [0,0]
sigma = [] #Covariance
for i in range(len(Y)):
    if Y[i] == 0:
        sum2[0] = sum2[0]+((X[i]-mew[0])**2)
    if Y[i] == 1:
        sum2[1] = sum2[1]+((X[i]-mew[1])**2)

for i in range(len(sum2)):
    sigma.append(sum2[i]/count[i])
    
print 'covariance:', sigma

covariance: [0.14227600000000001, 0.096500000000000016]


In [12]:
import math
membership = []
for j in X:
    member_temp = []
    for i in range(len(mew)):
        temp = -math.log(sigma[i])+math.log(alpha[i])
        member_temp.append(temp - (((j-mew[i])**2)*1.0/2*sigma[i]**2))
    membership.append(member_temp)
#print membership

In [14]:
'''The discriminant function is going to compare the two values obtained above, for each record in the dataset.
In this case it is a list.'''

predict = []
for i in membership:
    x = i[0] - i[1]
    if  x > 0:
        predict.append(0)
    else: predict.append(1)

print predict

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]


In [16]:
for i,j in zip(predict,Y):
    x = x + (i-j)**2
mse = x/len(predict)
print mse

0.664068347083


In [29]:
from sklearn.cross_validation import KFold
kf = KFold(len(Y), n_folds=10, shuffle = True)
cm_fold = []

In [30]:
for train_index, test_index in kf:
    X_train, X_test = X[train_index], X[test_index]
    Y_train, Y_test = Y[train_index], Y[test_index]
    
    count_tr = [0,0]
    for i in Y_train:
        if i == 0:
            count_tr[0] = count_tr[0]+1
        if i == 1:
            count_tr[1] = count_tr[1]+1
    
    alpha_tr = [] #no. of examples in a class/in the two classes chosen
    for i in count:
        alpha_tr.append(i * 1.0 / len(Y_train))
    
    sum1_tr = [0,0] #Sum of I(y(i)=j)*X(i) {Helps determining mew}
    for i in range(len(Y_train)):
        if Y_train[i] == 0:
            sum1_tr[0] = sum1_tr[0]+X_train[i]
        if Y_train[i] == 1:
            sum1_tr[1] = sum1_tr[1]+X_train[i]
    
    mew_tr = [] #mean of classes
    for i in range(len(sum1_tr)):
        mew_tr.append(sum1_tr[i]/count_tr[i])
    
    sum2_tr = [0,0]
    sigma_tr = [] #Covariance
    for i in range(len(Y_train)):
        if Y_train[i] == 0:
            sum2_tr[0] = sum2_tr[0]+((X_train[i]-mew_tr[0])**2)
        if Y_train[i] == 1:
            sum2_tr[1] = sum2_tr[1]+((X_train[i]-mew_tr[1])**2)
    for i in range(len(sum2_tr)):
        sigma_tr.append(sum2_tr[i]/count_tr[i])
     
    membership_ts = []
    for j in X_test:
        member_temp_ts = []
        for i in range(len(mew_tr)):
            temp_ts = -math.log(sigma_tr[i])+math.log(alpha_tr[i])
            member_temp_ts.append(temp_ts - (((j-mew_tr[i])**2)*1.0/2*sigma_tr[i]**2))
        membership_ts.append(member_temp_ts)
    
    predict_ts = []
    for i in membership_ts:
        xts = i[0] - i[1]
        if  xts > 0:
            predict_ts.append(0)
        else: predict_ts.append(1)
    
    for i,j in zip(predict_ts,Y_test):
        xts = xts + (i-j)**2
    mse_test = xts/len(predict_ts)
    
    clabels = [0,1]
    cm_ts = []
    for i in clabels:
        tmp =[0]*len(clabels)
        for j in range(len(Y_test)):
            #print j
            if Y_test[j] == i and Y_test[j] == predict_ts[j]:
                tmp[clabels.index(i)] += 1
            elif Y_test[j] == i and Y_test[j] != predict_ts[j]:
                tmp[clabels.index(predict_ts[j])] += 1
        cm_ts.append(tmp)
    cm_fold.append(cm_ts)

In [24]:
print predict_ts
print mse_test

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
0.586579871235


In [25]:
clabels = [0,1]
cm_ts = []
for i in clabels:
    tmp =[0]*len(clabels)
    for j in range(len(Y_test)):
        #print j
        if Y_test[j] == i and Y_test[j] == predict_ts[j]:
            tmp[clabels.index(i)] += 1
        elif Y_test[j] == i and Y_test[j] != predict_ts[j]:
            tmp[clabels.index(predict_ts[j])] += 1
    cm_ts.append(tmp)

In [32]:
cm_fold = np.array(cm_fold)

In [34]:
print cm_fold

[[[0 5]
  [0 5]]

 [[0 9]
  [0 1]]

 [[0 7]
  [0 3]]

 [[0 4]
  [0 6]]

 [[0 5]
  [0 5]]

 [[0 2]
  [0 8]]

 [[0 4]
  [0 6]]

 [[0 5]
  [0 5]]

 [[0 5]
  [0 5]]

 [[0 4]
  [0 6]]]


In [35]:
prec = []
for i in cm_fold:
    i = np.array(i)
    prec_tmp=[]
    try:
        prec_tmp.append(float(i[0,0])/np.sum(i,axis=0)[0])
    except ZeroDivisionError:
        prec_tmp.append(0)
    try:
        prec_tmp.append(float(i[1,1])/np.sum(i,axis=0)[1])
    except ZeroDivisionError:
        prec_tmp.append(0)   
    prec.append(prec_tmp)

In [36]:
print prec
np.mean(prec,axis=0)

[[0, 0.5], [0, 0.1], [0, 0.3], [0, 0.6], [0, 0.5], [0, 0.8], [0, 0.6], [0, 0.5], [0, 0.5], [0, 0.6]]


array([ 0. ,  0.5])

In [38]:
rec = []
for i in cm_fold:
    i = np.array(i)
    rec_tmp=[]
    try:
        rec_tmp.append(float(i[0,0])/np.sum(i,axis=1)[0])
    except ZeroDivisionError:
        rec_tmp.append(0)
    try:
        rec_tmp.append(float(i[1,1])/np.sum(i,axis=1)[1])
    except ZeroDivisionError:
        rec_tmp.append(0)   
    rec.append(rec_tmp)     
    
print rec
np.mean(rec,axis =0)

[[0.0, 1.0], [0.0, 1.0], [0.0, 1.0], [0.0, 1.0], [0.0, 1.0], [0.0, 1.0], [0.0, 1.0], [0.0, 1.0], [0.0, 1.0], [0.0, 1.0]]


array([ 0.,  1.])

In [39]:
F1 = [] #fmeasure
for i in range(len(prec)):
    tmp = []
    try:
        varr0 = 2*((prec[i][0]*rec[i][0])/(prec[i][0]+rec[i][0]))
        #print varr0
        tmp.append(varr0)
    except ZeroDivisionError:
        tmp.append(0)
    try:
        varr1 = 2*((prec[i][1]*rec[i][1])/(prec[i][1]+rec[i][1]))
        #print varr1
        tmp.append(varr1)
    except ZeroDivisionError:
        tmp.append(0)
    F1.append(tmp)

In [40]:
print F1
np.mean(F1,axis = 0)

[[0, 0.6666666666666666], [0, 0.18181818181818182], [0, 0.4615384615384615], [0, 0.7499999999999999], [0, 0.6666666666666666], [0, 0.888888888888889], [0, 0.7499999999999999], [0, 0.6666666666666666], [0, 0.6666666666666666], [0, 0.7499999999999999]]


array([ 0.        ,  0.64489122])

In [41]:
acc = []
for i in range(len(cm_fold)):
    acc1 = np.trace(cm_fold[i])*1.0/np.sum(cm_fold[i])
    acc.append(acc1)
print np.mean(acc)

0.5
