In [2]:
import matplotlib.pyplot as plt
from sklearn import datasets
import numpy as np
import math
from sklearn.cross_validation import KFold

In [3]:
iris = datasets.load_iris()

In [4]:
X = iris['data']
Y = iris['target']

In [5]:
X = np.array(X) #Data
Y = np.array(Y) #labels

In [6]:
count = [0,0,0]
for i in Y:
    if i == 0:
        count[0] = count[0]+1
    if i == 1:
        count[1] = count[1]+1
    if i == 2:
        count[2] = count[2]+1

In [7]:
alpha = [] #no. of examples in a class/in the two classes chosen
for i in count:
    alpha.append(i * 1.0 / len(Y))

print alpha

[0.3333333333333333, 0.3333333333333333, 0.3333333333333333]


In [8]:
class0 = []
class1 = []
class2 = []

for i in range(len(Y)):
    if Y[i] == 0:
        class0.append(X[i])
    elif Y[i]==1:
        class1.append(X[i])
    elif Y[i]==2:
        class2.append(X[i])    
        
class0 = np.array(class0)
class1 = np.array(class1)
class2 = np.array(class2)

In [9]:
mean_set1 = np.mean(class0, axis = 0) #along the columns
print mean_set1

[ 5.006  3.418  1.464  0.244]


In [10]:
mean_set2 = np.mean(class1, axis = 0) #along the columns
print mean_set2

[ 5.936  2.77   4.26   1.326]


In [11]:
mean_set3 = np.mean(class2, axis = 0) #along the columns
print mean_set3

[ 6.588  2.974  5.552  2.026]


In [12]:
tempClass0 = []
for i in range(len(class0)):
    tempClass0.append(class0[i] - mean_set1)

tempClass0 = np.array(tempClass0)

In [13]:
tempClass1 = []
for i in range(len(class1)):
    tempClass1.append(class1[i] - mean_set2)
    
tempClass1 = np.array(tempClass1)

In [14]:
tempClass2 = []
for i in range(len(class2)):
    tempClass2.append(class2[i] - mean_set3)
    
tempClass2 = np.array(tempClass2)

In [15]:
sigma0 = np.dot(tempClass0.transpose(),tempClass0)/(1.0*len(tempClass0))
print sigma0

[[ 0.121764  0.098292  0.015816  0.010336]
 [ 0.098292  0.142276  0.011448  0.011208]
 [ 0.015816  0.011448  0.029504  0.005584]
 [ 0.010336  0.011208  0.005584  0.011264]]


In [16]:
sigma1 = np.dot(tempClass1.transpose(),tempClass1)/(1.0*len(tempClass1))
print sigma1

[[ 0.261104  0.08348   0.17924   0.054664]
 [ 0.08348   0.0965    0.081     0.04038 ]
 [ 0.17924   0.081     0.2164    0.07164 ]
 [ 0.054664  0.04038   0.07164   0.038324]]


In [17]:
sigma2 = np.dot(tempClass2.transpose(),tempClass2)/(1.0*len(tempClass2))
print sigma2

[[ 0.396256  0.091888  0.297224  0.048112]
 [ 0.091888  0.101924  0.069952  0.046676]
 [ 0.297224  0.069952  0.298496  0.047848]
 [ 0.048112  0.046676  0.047848  0.073924]]


In [18]:
mem1 = []
for i in X:
    determinant1 = np.linalg.det(sigma0)
    var1 = np.dot((i-mean_set1).transpose(),np.linalg.inv(sigma0))
    var2 = np.dot(var1,(i-mean_set1))
    fin1 = math.log(alpha[0])-(math.log(determinant1))/float(2)- (var2)/float(2)
    mem1.append(fin1)

In [19]:
mem2 = []
for i in X:
    determinant2 = np.linalg.det(sigma1)
    var3 = np.dot((i-mean_set2).transpose(),np.linalg.inv(sigma1))
    var4 = np.dot(var3,(i-mean_set2))
    fin2 = math.log(alpha[1])-(math.log(determinant2))/float(2)- (var4)/float(2)
    mem2.append(fin2)

In [20]:
mem3 = []
for i in X:
    determinant3 = np.linalg.det(sigma2)
    var5 = np.dot((i-mean_set3).transpose(),np.linalg.inv(sigma2))
    var6 = np.dot(var5,(i-mean_set3))
    fin3 = math.log(alpha[2])-(math.log(determinant3))/float(2)- (var6)/float(2)
    mem3.append(fin3)

In [21]:
predict =[]
for i,j,k in zip(mem1,mem2,mem3):
    #print i,j
    if i>j and i>k:
        predict.append(0)
    elif j>i and j>k:
        predict.append(1)
    else: predict.append(2)

In [22]:
clabels = [0,1,2]
cm= []
for i in clabels:
    tmp =[0]*len(clabels)
    for j in range(len(Y)):
        #print j
        if Y[j] == i and Y[j] == predict[j]:
            tmp[clabels.index(i)] += 1
        elif Y[j] == i and Y[j] != predict[j]:
            tmp[clabels.index(predict[j])] += 1
    cm.append(tmp)

In [23]:
cm = np.matrix(cm)

In [24]:
accuracy = np.trace(cm)*1.0/np.sum(cm)
print accuracy

0.98


In [25]:
precision1 = float(cm[0,0])/np.sum(cm[:,0])
print precision1

1.0


In [26]:
precision2 = float(cm[1,1])/(np.sum(cm[:,1]))
print precision2

0.979591836735


In [27]:
precision3 = float(cm[2,2])/(np.sum(cm[:,2]))
print precision3

0.960784313725


In [28]:
recall1 = float(cm[0,0])/np.sum(cm,axis=1)[0]
print recall1

[[ 1.]]


In [29]:
recall2 = float(cm[1,1])/np.sum(cm,axis=1)[1]
print recall2

[[ 0.96]]


In [30]:
recall3 = float(cm[2,2])/np.sum(cm,axis=1)[2]
print recall3

[[ 0.98]]


In [31]:
fmeasure1 = 2*((precision1 * recall1)/(precision1 + recall1))

In [32]:
fmeasure2 = 2*((precision2 * recall2)/(precision2 + recall2))

In [33]:
fmeasure3 = 2*((precision3 * recall3)/(precision3 + recall3))

In [34]:
print fmeasure1
print fmeasure2
print fmeasure3

[[ 1.]]
[[ 0.96969697]]
[[ 0.97029703]]


In [35]:
kf = KFold(len(Y), n_folds=10, shuffle = True)
cm_fold = []

In [36]:
for train_index, test_index in kf:
    X_train, X_test = X[train_index], X[test_index]
    Y_train, Y_test = Y[train_index], Y[test_index]
    
    count_tr = [0,0,0]
    for i in Y_train:
        if i == 0:
            count_tr[0] = count_tr[0]+1
        if i == 1:
            count_tr[1] = count_tr[1]+1
        if i == 2:
            count_tr[2] = count_tr[2]+1
            
    alpha_tr = [] 
    for i in count_tr:
        alpha_tr.append(i * 1.0 / len(Y_train))

    class_tr0 = []
    class_tr1 = []
    class_tr2 = []
    for i in range(len(Y_train)):
        if Y_train[i] == 0:
            class_tr0.append(X_train[i])
        elif Y_train[i]==1:
            class_tr1.append(X_train[i])
        elif Y_train[i]==2:
            class_tr2.append(X_train[i])

    class_tr0 = np.array(class_tr0)
    class_tr1 = np.array(class_tr1)
    class_tr2 = np.array(class_tr2)
    
    mean_set_tr0 = np.mean(class_tr0, axis = 0)
    mean_set_tr1 = np.mean(class_tr1, axis = 0)
    mean_set_tr2 = np.mean(class_tr2, axis = 0)
    
    tempClass_tr0 = []
    for i in range(len(class_tr0)):
        tempClass_tr0.append(class_tr0[i] - mean_set_tr0)
    tempClass_tr1 = []
    for i in range(len(class_tr1)):
        tempClass_tr1.append(class_tr1[i] - mean_set_tr1)
    tempClass_tr2 = []
    for i in range(len(class_tr2)):
        tempClass_tr2.append(class_tr2[i] - mean_set_tr2)
    
    tempClass_tr0 = np.array(tempClass_tr0)
    tempClass_tr1 = np.array(tempClass_tr1)
    tempClass_tr2 = np.array(tempClass_tr2)
    
    sigma_tr0 = np.dot(tempClass_tr0.transpose(),tempClass_tr0)/(1.0*len(tempClass_tr0))
    sigma_tr1 = np.dot(tempClass_tr1.transpose(),tempClass_tr1)/(1.0*len(tempClass_tr1))
    sigma_tr2 = np.dot(tempClass_tr2.transpose(),tempClass_tr2)/(1.0*len(tempClass_tr2))
    
    mem1_tr = []
    for i in X_test:
        determinant1_tr = np.linalg.det(sigma_tr0)
        var1_tr = np.dot((i-mean_set_tr0).transpose(),np.linalg.pinv(sigma_tr0))
        var2_tr = np.dot(var1_tr,i-mean_set_tr0)
        #print "alpha", alpha_tr[0]
        #print "determinant1_tr", determinant1_tr
        fin1_tr = math.log(alpha_tr[0])-(math.log(determinant1_tr))/float(2)- (abs(var2_tr))/float(2)
        mem1_tr.append(fin1_tr)

    mem2_tr = []
    for i in X_test:
        determinant2_tr = np.linalg.det(sigma_tr1)
        var3_tr = np.dot((i-mean_set_tr1).transpose(),np.linalg.inv(sigma_tr1))
        var4_tr = np.dot(var3_tr,(i-mean_set_tr1))
        fin2_tr = math.log(alpha_tr[1])-(math.log(determinant2_tr)/float(2))- (var4_tr)/float(2)
        mem2_tr.append(fin2_tr)
        
    mem3_tr = []
    for i in X_test:
        determinant3_tr = np.linalg.det(sigma_tr2)
        var5_tr = np.dot((i-mean_set_tr2).transpose(),np.linalg.inv(sigma_tr2))
        var6_tr = np.dot(var5,(i-mean_set_tr2))
        fin3_tr = math.log(alpha_tr[2])-(math.log(determinant3_tr))/float(2)- (var6_tr)/float(2)
        mem3_tr.append(fin3_tr)
        
    clabels = [0,1,2]   
    predict_tr =[]
    for i,j,k in zip(mem1_tr,mem2_tr,mem3_tr):
        #print i,j
        #xx = max(i,j,k)
        #predict_tr.append([i,j,k].index(xx))
        if i>j and i>k:
            predict_tr.append(0)
        elif j>i and j>k:
            predict_tr.append(1)
        else:  predict_tr.append(2)
    #for i,j,k in zip(mem1_tr,mem2_tr,mem3_tr):
    #    print [i,j,k].index(max(i,j,k))
    
    cm1= []
    for i in clabels:
        tmp =[0]*len(clabels)
        for j in range(len(Y_test)):
            #print j
            if Y_test[j] == i and Y_test[j] == predict_tr[j]:
                tmp[clabels.index(i)] += 1
            elif Y_test[j] == i and Y_test[j] != predict_tr[j]:
                tmp[clabels.index(predict_tr[j])] += 1
        cm1.append(tmp)
    cm_fold.append(cm1)

In [37]:
cm_fold = np.array(cm_fold)

In [38]:
print cm_fold # 30 confusion matrices for 3 classes.

[[[4 0 0]
  [0 4 3]
  [0 0 4]]

 [[6 0 1]
  [0 2 4]
  [0 0 2]]

 [[5 0 0]
  [0 5 2]
  [0 0 3]]

 [[2 0 0]
  [0 5 1]
  [0 0 7]]

 [[3 0 0]
  [0 6 2]
  [0 0 4]]

 [[6 0 0]
  [0 0 3]
  [0 0 6]]

 [[4 0 0]
  [0 2 1]
  [0 0 8]]

 [[6 0 2]
  [0 2 2]
  [0 0 3]]

 [[5 0 0]
  [0 1 2]
  [0 0 7]]

 [[5 0 1]
  [0 1 2]
  [0 0 6]]]


In [39]:
prec = []
for i in cm_fold:
    i = np.array(i)
    prec_tmp=[]
    try:
        prec_tmp.append(float(i[0,0])/np.sum(i,axis=0)[0])
    except ZeroDivisionError:
        prec_tmp.append(0)
    try:
        prec_tmp.append(float(i[1,1])/np.sum(i,axis=0)[1])
    except ZeroDivisionError:
        prec_tmp.append(0)
    try:
        prec_tmp.append(float(i[2,2])/np.sum(i,axis=0)[2])
    except ZeroDivisionError:
        prec_tmp.append(0)    
    prec.append(prec_tmp)            

In [40]:
print prec
np.mean(prec,axis=0)

[[1.0, 1.0, 0.5714285714285714], [1.0, 1.0, 0.2857142857142857], [1.0, 1.0, 0.6], [1.0, 1.0, 0.875], [1.0, 1.0, 0.6666666666666666], [1.0, 0, 0.6666666666666666], [1.0, 1.0, 0.8888888888888888], [1.0, 1.0, 0.42857142857142855], [1.0, 1.0, 0.7777777777777778], [1.0, 1.0, 0.6666666666666666]]


array([ 1.       ,  0.9      ,  0.6427381])

In [41]:
rec = []
for i in cm_fold:
    i = np.array(i)
    rec_tmp=[]
    try:
        rec_tmp.append(float(i[0,0])/np.sum(i,axis=1)[0])
    except ZeroDivisionError:
        rec_tmp.append(0)
    try:
        rec_tmp.append(float(i[1,1])/np.sum(i,axis=1)[1])
    except ZeroDivisionError:
        rec_tmp.append(0)
    try:
        rec_tmp.append(float(i[2,2])/np.sum(i,axis=1)[2])
    except ZeroDivisionError:
        rec_tmp.append(0)    
    rec.append(rec_tmp)     

In [42]:
print rec
np.mean(rec,axis =0)

[[1.0, 0.5714285714285714, 1.0], [0.8571428571428571, 0.3333333333333333, 1.0], [1.0, 0.7142857142857143, 1.0], [1.0, 0.8333333333333334, 1.0], [1.0, 0.75, 1.0], [1.0, 0.0, 1.0], [1.0, 0.6666666666666666, 1.0], [0.75, 0.5, 1.0], [1.0, 0.3333333333333333, 1.0], [0.8333333333333334, 0.3333333333333333, 1.0]]


array([ 0.94404762,  0.50357143,  1.        ])

In [44]:
F1 = []
for i in range(len(prec)):
    tmp = []
    try:
        varr0 = 2*(prec[i][0]*rec[i][0]/prec[i][0]+rec[i][0])
        tmp.append(varr0)
    except ZeroDivisionError:
        tmp.append(0)
    try:
        varr1 = 2*(prec[i][1]*rec[i][1]/prec[i][1]+rec[i][1])
        tmp.append(varr1)
    except ZeroDivisionError:
        tmp.append(0)
    try:
        varr2 = 2*(prec[i][2]*rec[i][2]/prec[i][2]+rec[i][2])
        tmp.append(varr2)
    except ZeroDivisionError:
        tmp.append(0)
    F1.append(tmp)

In [45]:
print F1
np.mean(F1,axis = 0)

[[4.0, 2.2857142857142856, 4.0], [3.4285714285714284, 1.3333333333333333, 4.0], [4.0, 2.857142857142857, 4.0], [4.0, 3.3333333333333335, 4.0], [4.0, 3.0, 4.0], [4.0, 0, 4.0], [4.0, 2.6666666666666665, 4.0], [3.0, 2.0, 4.0], [4.0, 1.3333333333333333, 4.0], [3.3333333333333335, 1.3333333333333333, 4.0]]


array([ 3.77619048,  2.01428571,  4.        ])

In [140]:
accuracy = np.trace(cm)*1.0/np.sum(cm)
print accuracy

0.5
0.555555555556
0.75
0.857142857143
0.833333333333
0.428571428571
0.6
0.777777777778
0.777777777778
0.5
0.5
0.555555555556
0.75
0.857142857143
0.833333333333
0.428571428571
0.6
0.777777777778
0.777777777778
0.5
0.5
0.555555555556
0.75
0.857142857143
0.833333333333
0.428571428571
0.6
0.777777777778
0.777777777778
0.5


In [58]:
acc = []
for i in range(len(cm_fold)):
    acc1 = np.trace(cm_fold[i])*1.0/np.sum(cm_fold[i])
    acc.append(acc1)
print np.mean(acc)

0.826666666667
