In [206]:
import numpy as np
from math import log ,factorial
from sklearn.cross_validation import KFold
from sklearn.metrics import accuracy_score, confusion_matrix, precision_score,recall_score,f1_score
from itertools import combinations
import matplotlib.pyplot as plt
%matplotlib inline
import io

In [207]:
filename = "spambase.data"
X = []
Y = []
for line in open(filename):
    #li=line.strip()
    var = line.split(',')
    Y.append(int(var[-1]))
    X.append(map(float,var[1:len(var)-1]))

In [208]:
X = np.array(X)
Y = np.array(Y)

In [209]:
#to obtain features that are 0 or 1.
x=[]
for listx in X:
    for number in range(len(listx)):
        if  listx[number]> 0.0:
            listx[number] = 1.0
    x.append(listx)
print np.shape(x)

(4601L, 56L)


In [210]:
class0 = []
class1 = []

for i in range(len(Y)):
    if Y[i] == 0:
        class0.append(x[i])
    elif Y[i]==1:
        class1.append(x[i])

In [211]:
print len(class0)

2788


In [212]:
alpha0 = []
alpha0.append((np.sum(class0,axis = 0))/ (len(class0)))
print alpha0

[array([ 0.09791966,  0.27725968,  0.00286944,  0.22022956,  0.11406026,
        0.01542324,  0.07352941,  0.07819225,  0.17037303,  0.05093257,
        0.42395983,  0.11908178,  0.04519369,  0.01757532,  0.09038737,
        0.0954089 ,  0.12553802,  0.58070301,  0.01685796,  0.34325681,
        0.00789096,  0.02761836,  0.01936872,  0.37302726,  0.28120516,
        0.276901  ,  0.15530846,  0.12912482,  0.16176471,  0.10401722,
        0.07281205,  0.12338594,  0.07352941,  0.15746055,  0.17467719,
        0.26111908,  0.01829268,  0.11549498,  0.09002869,  0.05272597,
        0.1151363 ,  0.10401722,  0.10043042,  0.29555237,  0.16104735,
        0.01578192,  0.06707317,  0.18615495,  0.55164993,  0.14311334,
        0.267934  ,  0.1043759 ,  0.08213773,  1.        ,  1.        ,  1.        ])]


In [213]:
alpha1 = []
alpha1.append((np.sum(class1,axis = 0))/ (len(class1)))
print alpha1

[array([  3.44732488e-01,   6.15002758e-01,   2.15113072e-02,
         6.25482625e-01,   3.75620518e-01,   4.21400993e-01,
         3.41423056e-01,   3.06122449e-01,   4.56150028e-01,
         3.12741313e-01,   6.30446773e-01,   2.86817430e-01,
         1.27413127e-01,   1.58301158e-01,   5.45504688e-01,
         3.84445670e-01,   3.79481522e-01,   8.86927744e-01,
         2.07942637e-01,   8.08604523e-01,   5.23993381e-02,
         3.32046332e-01,   3.75620518e-01,   2.75785990e-02,
         1.48924435e-02,   4.41257584e-03,   1.65471594e-02,
         6.61886376e-03,   9.92829564e-03,   1.65471594e-03,
         1.10314396e-03,   3.36458908e-02,   5.51571980e-03,
         2.53723111e-02,   6.17760618e-02,   5.57087700e-02,
         1.76503034e-02,   3.41974628e-02,   1.11417540e-01,
         5.51571980e-04,   1.10314396e-02,   4.68836183e-02,
         2.59238831e-02,   2.68615554e-01,   3.75068946e-02,
         1.04798676e-02,   8.82515168e-03,   1.49476007e-01,
         6.49200221e-01

In [214]:
prior0 = 0
prior0 = float(len(class0))/float(len(x))
print prior0
logp0 = log(prior0)

0.605955227125


In [215]:
prior1 = 0
prior1 = float(len(class1))/float(len(x))
print prior1
logp1 = log(prior1)

0.394044772875


In [216]:
a = []
d=0
u = np.array(x)
for i in range(len(alpha0)):
    for j in range(len(u)):
        d=0
        for k in range(len(u[j])):
            #print u[i][j]
            if u[j][k]==1:
                d += np.log(alpha0[i][k])
            else:
                d += np.log(1-alpha0[i][k])
        d+np.log(prior0)
        a.append(d)
#print a

In [217]:
b = []
de=0
v = np.array(x)
for i in range(len(alpha1)):
    for j in range(len(v)):
        de=0
        for k in range(len(v[j])):
            #print v[i][j]
            if v[j][k]==1:
                de += np.log(alpha1[i][k])
            else:
                de += np.log(1-alpha1[i][k])
        de+np.log(prior1)
        b.append(de)
#print b

In [218]:
predict = []
for i,j in zip(a,b):
    if i>j:
        predict.append(0)
    else: predict.append(1)

In [224]:
#print predict

In [220]:
clabels = [0,1]
cm= []
for i in clabels:
    tmp1 =[0]*len(clabels)
    for j in range(len(Y)):
        #print j
        if Y[j] == i and Y[j] == predict[j]:
            tmp1[clabels.index(i)] += 1
        elif Y[j] == i and Y[j] != predict[j]:
            tmp1[clabels.index(predict[j])] += 1
    cm.append(tmp1)

In [222]:
cm = np.matrix(cm)
print cm

[[2591  197]
 [ 305 1508]]


In [223]:
kf = KFold(len(Y), n_folds=10, shuffle = True)
cm_fold = []

In [246]:
for train_index, test_index in kf:
    X_train, X_test = X[train_index], X[test_index]
    Y_train, Y_test = Y[train_index], Y[test_index]
    
    xtr=[]
    for listxtr in X_train:
        for numbertr in range(len(listxtr)):
            if  listxtr[numbertr]> 0.0:
                listxtr[numbertr] = 1.0
        xtr.append(listxtr)
    #print np.shape(xtr)
    
    xts=[]
    for listxts in X_test:
        for numberts in range(len(listxts)):
            if  listxts[numberts]> 0.0:
                listxts[numberts] = 1.0
        xts.append(listxts)
    
    class0_tr = []
    class1_tr = []

    for i in range(len(Y_train)):
        if Y_train[i] == 0:
            class0_tr.append(xtr[i])
        elif Y_train[i]==1:
            class1_tr.append(xtr[i])
    
    alpha0_tr = []
    alpha0_tr.append((np.sum(class0_tr,axis = 0))/ (len(class0_tr)))
    #print alpha0_tr
    
    alpha1_tr = []
    alpha1_tr.append((np.sum(class1_tr,axis = 0))/ (len(class1_tr)))
    #print alpha1_tr
    
    prior0tr = 0
    prior0tr = float(len(class0_tr))/float(len(xtr))
    
    prior1tr = 0
    prior1tr = float(len(class1_tr))/float(len(xtr))
    
    ats = []
    dts=0
    utr = np.array(xts)
    for i in range(len(alpha0_tr)):
        for j in range(len(utr)):
            dts=0 #So that every itreration it sets back to zero. Due to which we get appropriate values.
            for k in range(len(utr[j])):
                #print u[i][j]
                if utr[j][k]==1:
                    dts += np.log(alpha0_tr[i][k])
                else:
                    dts += np.log(1-alpha0_tr[i][k])
            dts+np.log(prior0tr)
            ats.append(dts)
            
    ats1 = []
    dts1=0
    utr1 = np.array(xts)
    for i in range(len(alpha1_tr)):
        for j in range(len(utr1)):
            dts1=0 #So that every itreration it sets back to zero. Due to which we get appropriate values.
            for k in range(len(utr[j])):
                #print u[i][j]
                if utr[j][k]==1:
                    dts1 += np.log(alpha1_tr[i][k])
                else:
                    dts1 += np.log(1-alpha1_tr[i][k])
            dts1+np.log(prior1tr)
            ats1.append(dts1)
            
    predict_ts = []
    for i,j in zip(ats,ats1):
        if i>j:
            predict_ts.append(0)
        else: predict_ts.append(1)
            
    clabels = [0,1]
    cm_test= []
    for i in clabels:
        tmp =[0]*len(clabels)
        for j in range(len(Y_test)):
            if Y_test[j] == i and Y_test[j] == predict_ts[j]:
                tmp[clabels.index(i)] += 1
            elif Y_test[j] == i and Y_test[j] != predict_ts[j]:
                tmp[clabels.index(predict_ts[j])] += 1
        cm_test.append(tmp)
    cm_fold.append(cm_test)

C:\Anaconda\lib\site-packages\IPython\kernel\__main__.py:67: RuntimeWarning: divide by zero encountered in log


In [257]:
cm_fold = np.array(cm_fold)

In [258]:
cm_fold

array([[[270,  16],
        [ 23, 152]],

       [[259,  18],
        [ 29, 154]],

       [[281,  15],
        [ 21, 143]],

       [[257,  16],
        [ 35, 152]],

       [[257,  19],
        [ 31, 153]],

       [[259,  29],
        [ 30, 142]],

       [[263,  26],
        [ 30, 141]],

       [[258,  17],
        [ 30, 155]],

       [[258,  19],
        [ 35, 148]],

       [[229,  22],
        [ 41, 168]],

       [[270,  16],
        [ 23, 152]],

       [[259,  18],
        [ 29, 154]],

       [[281,  15],
        [ 21, 143]],

       [[257,  16],
        [ 35, 152]],

       [[257,  19],
        [ 31, 153]],

       [[259,  29],
        [ 30, 142]],

       [[263,  26],
        [ 30, 141]],

       [[258,  17],
        [ 30, 155]],

       [[258,  19],
        [ 35, 148]],

       [[229,  22],
        [ 41, 168]]])

In [259]:
prec = []
for i in cm_fold:
    i = np.array(i)
    prec_tmp=[]
    try:
        prec_tmp.append(float(i[0,0])/np.sum(i,axis=0)[0])
    except ZeroDivisionError:
        prec_tmp.append(0)
    try:
        prec_tmp.append(float(i[1,1])/np.sum(i,axis=0)[1])
    except ZeroDivisionError:
        prec_tmp.append(0)   
    prec.append(prec_tmp) 

In [260]:
print prec
np.mean(prec,axis=0)

[[0.9215017064846417, 0.9047619047619048], [0.8993055555555556, 0.8953488372093024], [0.9304635761589404, 0.9050632911392406], [0.8801369863013698, 0.9047619047619048], [0.8923611111111112, 0.8895348837209303], [0.8961937716262975, 0.8304093567251462], [0.8976109215017065, 0.844311377245509], [0.8958333333333334, 0.9011627906976745], [0.8805460750853242, 0.8862275449101796], [0.8481481481481481, 0.8842105263157894], [0.9215017064846417, 0.9047619047619048], [0.8993055555555556, 0.8953488372093024], [0.9304635761589404, 0.9050632911392406], [0.8801369863013698, 0.9047619047619048], [0.8923611111111112, 0.8895348837209303], [0.8961937716262975, 0.8304093567251462], [0.8976109215017065, 0.844311377245509], [0.8958333333333334, 0.9011627906976745], [0.8805460750853242, 0.8862275449101796], [0.8481481481481481, 0.8842105263157894]]


array([ 0.89421012,  0.88457924])

In [261]:
rec = []
for i in cm_fold:
    i = np.array(i)
    rec_tmp=[]
    try:
        rec_tmp.append(float(i[0,0])/np.sum(i,axis=1)[0])
    except ZeroDivisionError:
        rec_tmp.append(0)
    try:
        rec_tmp.append(float(i[1,1])/np.sum(i,axis=1)[1])
    except ZeroDivisionError:
        rec_tmp.append(0) 
    rec.append(rec_tmp)     

In [262]:
print rec
np.mean(rec,axis=0)

[[0.9440559440559441, 0.8685714285714285], [0.9350180505415162, 0.8415300546448088], [0.9493243243243243, 0.8719512195121951], [0.9413919413919414, 0.8128342245989305], [0.9311594202898551, 0.8315217391304348], [0.8993055555555556, 0.8255813953488372], [0.9100346020761245, 0.8245614035087719], [0.9381818181818182, 0.8378378378378378], [0.9314079422382672, 0.8087431693989071], [0.9123505976095617, 0.8038277511961722], [0.9440559440559441, 0.8685714285714285], [0.9350180505415162, 0.8415300546448088], [0.9493243243243243, 0.8719512195121951], [0.9413919413919414, 0.8128342245989305], [0.9311594202898551, 0.8315217391304348], [0.8993055555555556, 0.8255813953488372], [0.9100346020761245, 0.8245614035087719], [0.9381818181818182, 0.8378378378378378], [0.9314079422382672, 0.8087431693989071], [0.9123505976095617, 0.8038277511961722]]


array([ 0.92922302,  0.83269602])

In [263]:
F1 = [] #fmeasure
for i in range(len(prec)):
    tmp = []
    try:
        varr0 = 2*((prec[i][0]*rec[i][0])/(prec[i][0]+rec[i][0]))
        #print varr0
        tmp.append(varr0)
    except ZeroDivisionError:
        tmp.append(0)
    try:
        varr1 = 2*((prec[i][1]*rec[i][1])/(prec[i][1]+rec[i][1]))
        #print varr1
        tmp.append(varr1)
    except ZeroDivisionError:
        tmp.append(0)
    F1.append(tmp)

In [264]:
print F1
np.mean(F1,axis = 0)

[[0.9326424870466322, 0.8862973760932944], [0.9168141592920354, 0.867605633802817], [0.939799331103679, 0.8881987577639753], [0.9097345132743362, 0.856338028169014], [0.9113475177304966, 0.8595505617977529], [0.8977469670710572, 0.8279883381924199], [0.9037800687285223, 0.834319526627219], [0.9165186500888101, 0.8683473389355741], [0.9052631578947368, 0.8457142857142858], [0.8790786948176582, 0.8421052631578947], [0.9326424870466322, 0.8862973760932944], [0.9168141592920354, 0.867605633802817], [0.939799331103679, 0.8881987577639753], [0.9097345132743362, 0.856338028169014], [0.9113475177304966, 0.8595505617977529], [0.8977469670710572, 0.8279883381924199], [0.9037800687285223, 0.834319526627219], [0.9165186500888101, 0.8683473389355741], [0.9052631578947368, 0.8457142857142858], [0.8790786948176582, 0.8421052631578947]]


array([ 0.91127255,  0.85764651])

In [265]:
acc = []
for i in range(len(cm_fold)):
    acc1 = np.trace(cm_fold[i])*1.0/np.sum(cm_fold[i])
    acc.append(acc1)
print np.mean(acc)

0.890887956239
