In [1]:
import io
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model
from sklearn.linear_model import LinearRegression
#from sympy.solvers import solve
%matplotlib inline
filename = "svar-set2.dat.txt"
X = []
Y = []
for line in open(filename):
    li=line.strip()
    if not li.startswith("#"):
        var = line.split()
        Y.append([float(var[-1])])
        X.append([float(i) for i in var[0:len(var)-1]])

In [2]:
Z = []
Z = X
for i in Z:
    i.insert(0,1)

In [3]:
Z_chunk1_train = X[0:150]
Z_chunk2_train = X[0:100]
Z_chunk3_train = X[0:60]
Z_chunk_test = Z[-50:]
Y_chunk1_train =Y[0:150]
Y_chunk2_train = Y[0:100]
Y_chunk3_train = Y[0:60]
Y_chunk_test = Y[-50:]

print len(Z_chunk_test)

50


In [4]:
theta_chunk1 = np.linalg.solve((np.dot(np.array(Z_chunk1_train).transpose(),np.array(Z_chunk1_train))),
                           (np.dot(np.array(Z_chunk1_train).transpose(),np.array(Y_chunk1_train))))

print theta_chunk1

[[ 0.32615745]
 [-0.07842592]]


In [5]:
theta_chunk2 = np.linalg.solve((np.dot(np.array(Z_chunk2_train).transpose(),np.array(Z_chunk2_train))),
                           (np.dot(np.array(Z_chunk2_train).transpose(),np.array(Y_chunk2_train))))

print theta_chunk2

[[ 0.35441417]
 [-0.08161208]]


In [6]:
theta_chunk3 = np.linalg.solve((np.dot(np.array(Z_chunk3_train).transpose(),np.array(Z_chunk3_train))),
                           (np.dot(np.array(Z_chunk3_train).transpose(),np.array(Y_chunk3_train))))

print theta_chunk3

[[ 0.27967643]
 [-0.06469691]]


In [7]:
predict1 = []
for i in Z_chunk_test:
    predict1.append(np.dot(np.array(theta_chunk1).transpose(),np.array(i)))
    
predict2 = []
for j in Z_chunk_test:
    predict2.append(np.dot(np.array(theta_chunk2).transpose(),np.array(j)))

predict3 = []
for k in Z_chunk_test:
    predict3.append(np.dot(np.array(theta_chunk3).transpose(),np.array(k)))

In [8]:
for i in Y_chunk_test:
    sumd = 0
    for m,n in zip(predict1,Y_chunk_test):
        sumd = sumd + (m[0]-n[0])**2
    MSE_test1 = sumd/len(predict1)
    
for j in Y_chunk_test:
    sumd = 0
    for m,n in zip(predict2,Y_chunk_test):
        sumd = sumd + (m[0]-n[0])**2
    MSE_test2 = sumd/len(predict2)
    
for k in Y_chunk_test:
    sumd = 0
    for m,n in zip(predict3,Y_chunk_test):
        sumd = sumd + (m[0]-n[0])**2
    MSE_test3 = sumd/len(predict3)

In [10]:
print "MSEtest for 150 items tested on 50 items:", MSE_test1
print "MSEtest for 100 items tested on 50 items:", MSE_test2
print "MSEtest for 60 items tested on 50 items:", MSE_test3

MSEtest for 150 items tested on 50 items: 0.0531134130605
MSEtest for 100 items tested on 50 items: 0.0522352162825
MSEtest for 60 items tested on 50 items: 0.0537518240839
